### ISSUE TITLE
是否可以将一些配置暴露出来？

### ISSUE THREAD

**Issue by zhanbei1** [FunAudioLLM/CosyVoice#131]
我在本地部署了我们的Cosy Voice，体验下来非常棒，我已经有一些使用它的小创意了。再次感谢项目组的辛苦付出。

我的环境：
我使用的一个我的一个旧电脑，CPU i7 8核心，一个AMD显卡 2G显存，内存16G，操作系统为Centos7。

1、关于CPU资源使用：我发现在使用的过程中，并没有把我的CPU资源给占满，而且我也没有发现配置进程数量的地方（可能是我没找到），是否可以默认将输入的文本按照CPU的核心数然后切分，然后进行推理（当时可能要保持最小token数量）。我不确定这样是否可以加速生成。
2、关于GPU资源：我本地默认有一个AMD的显卡，但是我发现在使用过程中，默认并没有使用GPU，不确定是否我操作的不对。不知道这个是否可以配置
3、关于启动webui.py的demo 页面：我按照README.md的说明操作之后（而且README.md上缺少对硬件资源的需求，导致我第一次部署的时候，低估了需要的资源，这个是否也可以补充？？），发现启动webui.py 会缺少很多依赖，是否可以打一个全量的requirement.txt
4、关于模型文件：我们的模型文件都有点大，不知道后面是否进行压缩，通过git clone下拉压缩文件然后本地自己解压即可

再次感谢项目组所有同学的付出，和开源精神。

**Comment by aluminumbox** [comment]
we only provide the basic inference implementation. 
1. you need to use multiprocess in order to use multiple cpu, or python will continue to use only 1 gpu due to gil, unless your core library like numpy it already have multiple gpu support
2. maybe your gpu is not supported, cuda toolkit is only supported on Nvidia
3. the requirements.txt contains the full package needed to run the repo. we may add some hardware resource requirements later
4. I don't think zip will reduce the file size significantly because it is already pt format. We want the resource listed on repo for a clearer view

**Comment by zhanbei1** [comment]
> we only provide the basic inference implementation.
> 
> 1. you need to use multiprocess in order to use multiple cpu, or python will continue to use only 1 gpu due to gil, unless your core library like numpy it already have multiple gpu support
> 2. maybe your gpu is not supported, cuda toolkit is only supported on Nvidia
> 3. the requirements.txt contains the full package needed to run the repo. we may add some hardware resource requirements later
> 4. I don't think zip will reduce the file size significantly because it is already pt format. We want the resource listed on repo for a clearer view

OK ，Let me learn more about this project. The issue is closed
